spring:
  application:
    name: template
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajindustrytech@gmail.com
    password: bljw yajy bsbq npqz
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true